var fs = require('fs')
fs.mkdirSync("hello")
fs.writeFileSync('hello/hi.txt',"how are you!")
fs.appendFileSync('hello/hi.txt',"\nGood")
var data = fs.readFileSync('hello/hi.txt','utf-8')
fs.renameSync('hello/hi.txt','hello/user.txt')
console.log(data)
fs.unlinkSync('hello/user.txt')
fs.rmdirSync('hello')